spring:
  datasource:
    druid:
      url: jdbc:mysql://127.0.0.1:3306/suixingpay_config?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&zeroDateTimeBehavior=convertToNull
      username: xxxxx
      password: xxxxx
      driver-class-name: com.mysql.jdbc.Driver
      filters: stat,wall
      initialSize: 5
      minIdle: 5
      maxActive: 50
      maxWait: 60000
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: select 1 from dual
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 20
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000


  redis:
    host: 127.0.0.1
    port: 6379
    pool:
      maxWait: 1500
      maxActive: 2048
      minIdle: 20
      maxIdle: 200

suixingpay:
  autoload:
    cache:
      enable: true
  security:
    username: admin
    password: 123456
