spring:
  datasource:
    druid:
      url: jdbc:mysql://localhost:3306/suixingpay_config?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Shanghai
      username: root
      password: 123456
      driver-class-name: com.mysql.cj.jdbc.Driver
      filters: stat,wall
      initial-size: 5
      min-idle: 5
      max-active: 50
      max-wait: 60000
      time-between-eviction-runs-millis: 60000
      min-evictableidle-time-millis: 300000
      validation-query: select 1 from dual
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000

  redis:
    host: 172.16.136.146
    port: 6379
    jedis:
      pool:
        max-wait: 1500ms
        max-active: 2048
        min-idle: 20
        max-idle: 200

suixingpay:
  autoload:
    cache:
      enable: true
  security: # 客户端安全校验用户名和密码
    username: admin
    password: 123456
